image: Visual Studio 2017
clone_folder: c:\projects\Propaga
configuration: Release

environment:
    WORKSPACE: C:\projects
    matrix:
    - platform: Cygwin64
      COMPILER: cygwin
      CYGWIN_NOWINPATH: yes
      CYGSH: C:\cygwin64\bin\bash -c
    - platform: Win32
      COMPILER: vs

install:
  - if [%COMPILER%]==[vs] cinst cmake.install ninja
  - if [%COMPILER%]==[vs] SET "PATH=C:\Program Files\CMake\bin;%PATH%"
  - if [%COMPILER%]==[vs] call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x86
  - if [%COMPILER%]==[cygwin] SET "PATH=C:\cygwin64\bin;C:\cygwin64\usr\bin;%PATH%"
  - if [%COMPILER%]==[cygwin] SET PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - git submodule -q update --init --recursive
  - cd %WORKSPACE%
  - mkdir cygwin-downloads
  - ps: if($env:COMPILER -eq "cygwin") { Invoke-WebRequest https://cygwin.com/setup-x86_64.exe -OutFile $env:WORKSPACE\cygwin-setup.exe }
  - if [%COMPILER%]==[cygwin] %WORKSPACE%\cygwin-setup.exe --quiet-mode --no-shortcuts --no-startmenu --no-desktop --upgrade-also --root C:\cygwin64 --local-package-dir %WORKSPACE%\cygwin-downloads --packages gcc-g++,libopenmpi-devel,cmake,ninja,zlib-devel
  - ps: if($env:COMPILER -eq "vs") { Invoke-WebRequest https://download.microsoft.com/download/A/E/0/AE002626-9D9D-448D-8197-1EA510E297CE/msmpisetup.exe -OutFile $env:WORKSPACE\msmpi.exe }
  - if [%COMPILER%]==[vs] %WORKSPACE%\msmpi.exe -unattend
  - git clone https://github.com/Microsoft/vcpkg
  - cd vcpkg
  - if [%COMPILER%]==[vs] bootstrap-vcpkg.bat
  - if [%COMPILER%]==[vs] vcpkg integrate install
  - if [%COMPILER%]==[vs] vcpkg install msmpi
  - cd %WORKSPACE%\Propaga\
  - mkdir build
  - cd build
  - if [%COMPILER%]==[cygwin] %CYGSH% 'cmake /cygdrive/c/projects/Propaga -G "Ninja" -DCMAKE_BUILD_TYPE="Debug"'
  - if [%COMPILER%]==[vs]     cmake .. -G "Ninja" -DCMAKE_TOOLCHAIN_FILE=%WORKSPACE%\vcpkg\scripts\buildsystems\vcpkg.cmake -DCMAKE_BUILD_TYPE="Debug"

build_script:
  - if [%COMPILER%]==[cygwin] %CYGSH% 'cmake --build . --target install'
  - if [%COMPILER%]==[vs]     cmake --build . --target install
  -
